insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Marissa Glaves', 1, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Darb Hammerberger', 3, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Currey Copas', 1, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Wilbur Dutnall', 1, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Margo Stoodley', 3, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Gav Tysack', 2, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Stepha Litherland', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Quintina MacDonough', 3, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Binny Bertelsen', 1, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Somerset Paunton', 2, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Egbert Huston', 1, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Ashly Rishworth', 4, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Moina Casarino', 3, 0, 3);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Jamesy Kobisch', 2, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Sloan Gosford', 1, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Caesar Arndt', 2, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Judy Jane', 4, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Ivan Restall', 1, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Janos Vaughn', 2, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Corine Fann', 3, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Roobbie Hogben', 2, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Baily Daenen', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Rosina Connop', 2, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Cherise McCullen', 4, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Maurene Joseland', 2, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Kerry Bruce', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Karyl Alenin', 3, 0, 3);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Berta Fritchley', 4, 0, 3);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Binnie Yakov', 3, 0, 3);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Glennie Breit', 4, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Che Zannini', 2, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Bernhard Saffran', 4, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Kelcey Tissier', 2, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Abrahan Coultar', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Bryon Dmtrovic', 4, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Anica Plitz', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Cello Nurse', 4, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Madge Dorracott', 1, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Wilbur Ettridge', 5, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Kelsi Errichi', 2, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Caril Roe', 4, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Jessalyn Pailin', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Genevieve Duran', 4, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Jakie Lared', 5, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Edvard Billows', 1, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Noland Largan', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Dirk Scothorn', 2, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Alexis O''Curran', 2, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Rudolf Southernwood', 3, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Edward Pandya', 1, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Lonnie Wrightem', 3, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Leontyne Davidove', 2, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Nichols Kendrick', 1, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Farrand Gaitskill', 1, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Machine', 'Giana Kindon', 4, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Bondie Fern', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Breanne Laible', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Nedi Wyd', 1, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Lucina Solomonides', 3, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Nikolia Moodey', 5, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Rubetta Dilliston', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Beulah Kintish', 2, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Stearne Dunton', 3, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Briant Kienlein', 4, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Calley Maffezzoli', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Lezley Halford', 3, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Mirabella Coleyshaw', 5, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Shay Edwinson', 1, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Lyon Beckitt', 3, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Wilhelmine Huie', 5, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Estell Menloe', 5, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Gayelord Krahl', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Salvatore Pearl', 5, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Adore Andrei', 5, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Randall Ryves', 3, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Dorita Beynke', 1, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Ranna Corn', 3, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Programming Languages', 'Myrna Trass', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Dael Laidlaw', 5, 0, 5);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Weston Schirak', 1, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algebra', 'Bettine Wort', 4, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Garvey Delea', 1, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Augie Sampson', 3, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Harmonie Bennit', 3, 0, 6);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Linoel Likly', 5, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Marie-jeanne Bengle', 1, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Suellen Wallett', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Mallissa Ridesdale', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Zandra Cowdrey', 5, 0, 2);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Calculus', 'Britta Girardini', 2, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Cristi Hiseman', 5, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Neils Ennew', 5, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Lorain Ribeiro', 4, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Shelli Sweynson', 2, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Floria Chafney', 4, 0, 1);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Networking', 'Cathrine Goodbourn', 3, 0, 4);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Sherman Fotitt', 4, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Algorithm', 'Jarrad Treske', 3, 0, 8);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Transfer of Energy', 'Bernita Du Hamel', 2, 0, 7);
insert into Books (Title, Author, Price, Ordered, BookCategoryIdID) values ('Hardware', 'Jamison Melson', 4, 0, 6);